### ISSUE TITLE
docs: Module Docus

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/nuxt-markuplint#2]
## Description

モジュールドキュメントを作成する

### Env
- uses [Docus](https://docus.dev/)

### TODO

- [ ] docs: Introduction
- [ ] docs: Getting Started - Setup
- [ ] docs: Getting Started - Options
- [ ] docs: Markuplint - Config
- [ ] docs: Examples - Basic Usage
